### ISSUE TITLE
Moodle 3.5 version?

### ISSUE THREAD

**Issue by Jarvil** [projectestac/moodle-atto_fontfamily#7]
Hello,

Are you planning releasing Moodle 3.5 version?

**Comment by toniginard** [comment]
Hi,

We haven't tested the plugin in Moodle 3.5, but it should work because we've been using it in Moodle 3.4 and Moodle 3.6.

We won't release specific packages for different Moodle versions because we maintain this plugin just for our Moodle platform. The code is published, but we won't give support to it.


Best wishes,
